openapi: 3.2.0
info:
  description: This is the API documentation for Root.io.
  title: Root.io Billing API
  termsOfService: https://www.root.io/terms-of-service
  contact: {}
  version: '1.0'
servers:
- url: https://api.root.io
tags:
- name: Billing
paths:
  /v3/billing:
    get:
      security:
      - BasicAuth: []
      description: Retrieves the billing record for the authenticated user's organization
      tags:
      - Billing
      summary: Get billing for current organization
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillingResponseV3'
      operationId: getV3Billing
      x-operation-id-source: derived
components:
  schemas:
    BillingResponseV3:
      type: object
      properties:
        created_at:
          type: string
        entitlements:
          type: array
          items:
            type: string
        id:
          type: string
        organization_id:
          type: string
        sla_activated_at:
          type: string
        updated_at:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
