openapi: 3.2.0
info:
  description: This is the API documentation for Root.io.
  title: Root.io Cve Feed API
  termsOfService: https://www.root.io/terms-of-service
  contact: {}
  version: '1.0'
servers:
- url: https://api.root.io
tags:
- name: CveFeed
paths:
  /external/cve_feed:
    get:
      description: Downloads and returns JSON data from S3 for CVE feed consumption. No authentication required.
      tags:
      - CveFeed
      summary: Get CVE feed data
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
      operationId: getExternalCveFeed
      x-operation-id-source: derived
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
